/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Connection.Conectar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Itach
 */
public class FuncTela extends javax.swing.JFrame {

    private final Conectar objCon;
    
    public FuncTela() {
        initComponents();

        setResizable(false);

        setLocationRelativeTo(null);

        objCon = new Conectar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        teste = new javax.swing.JButton();
        cnpj_mask = new javax.swing.JLabel();
        cnpj_noMask = new javax.swing.JLabel();
        data_barras = new javax.swing.JLabel();
        data_tracos = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cb_tipoDocumento = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        c_documento = new javax.swing.JFormattedTextField();
        doc_noMask = new javax.swing.JLabel();
        doc_mask = new javax.swing.JLabel();
        cpf_mask = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jdData = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teste.setText("Validar");
        teste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testeActionPerformed(evt);
            }
        });
        jPanel2.add(teste, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 90, 40));

        cnpj_mask.setText("   ");
        jPanel2.add(cnpj_mask, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 421, 141, -1));

        cnpj_noMask.setText("   ");
        jPanel2.add(cnpj_noMask, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 421, 141, -1));

        data_barras.setText("   ");
        jPanel2.add(data_barras, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 446, 141, -1));

        data_tracos.setText("   ");
        jPanel2.add(data_tracos, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 446, 143, -1));

        jLabel11.setText("Tipo Documento:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        cb_tipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "CPF", "CNPJ" }));
        cb_tipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoDocumentoActionPerformed(evt);
            }
        });
        jPanel2.add(cb_tipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 82, -1));

        jLabel12.setText("Documento:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        c_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_documentoActionPerformed(evt);
            }
        });
        jPanel2.add(c_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, -1));

        doc_noMask.setText("   ");
        jPanel2.add(doc_noMask, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 110, -1));

        doc_mask.setText("   ");
        jPanel2.add(doc_mask, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 120, -1));

        cpf_mask.setText("   ");
        jPanel2.add(cpf_mask, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 137, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, 10));

        jdData.setDateFormatString("yyyy/MM/dd  HH:mm:ss");
        jPanel2.add(jdData, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Itach\\OneDrive\\Área de Trabalho\\ipoint2.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jFormattedTextField1.setText("jFormattedTextField1");
        jPanel2.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_documentoActionPerformed

    private void cb_tipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoDocumentoActionPerformed
        int tipoDoc = cb_tipoDocumento.getSelectedIndex();
        c_documento.setValue(null);
        switch (tipoDoc) {
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Selecione um tipo de documento!");
                break;
            case 1:
                c_documento.setFormatterFactory(CPF.getFormat());
                break;
            case 2:
                c_documento.setFormatterFactory(CNPJ.getFormat());
                break;
        }
    }//GEN-LAST:event_cb_tipoDocumentoActionPerformed

    private void testeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testeActionPerformed
            
        try {
            objCon.openConnection();
            String SQL = "select * from admin where cpf = '078.322.033-23'";
            PreparedStatement ps = objCon.con.prepareStatement(SQL);
            objCon.rs = ps.executeQuery();
            objCon.rs.next();
            if (c_documento.getText().equals(objCon.rs.getString("cpf"))) {
                
                JOptionPane.showMessageDialog(null, "Voce fez o Check-IN no iPoint!");
                DataHora();
            } else {
                JOptionPane.showMessageDialog(null, "CPF ou CNPJ não cadastrado!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_testeActionPerformed

    public void DataHora() {

        String SQL = "INSERT INTO registrar (data_hora, cpf) VALUES (?, ?)";
        try {
            PreparedStatement pst = objCon.con.prepareStatement(SQL);
            pst.setString(1,((JTextField)jdData.getDateEditor().getUiComponent()).getText()); 
            pst.setString(2,((JTextField)c_documento).getText());
            int executeUpdate = pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Hora e Data registrada " + executeUpdate);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao registrar verifique os dados " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField c_documento;
    private javax.swing.JComboBox cb_tipoDocumento;
    private javax.swing.JLabel cnpj_mask;
    private javax.swing.JLabel cnpj_noMask;
    private javax.swing.JLabel cpf_mask;
    private javax.swing.JLabel data_barras;
    private javax.swing.JLabel data_tracos;
    private javax.swing.JLabel doc_mask;
    private javax.swing.JLabel doc_noMask;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdData;
    private javax.swing.JButton teste;
    // End of variables declaration//GEN-END:variables

    private void executeUpdate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
